FROM scalabase:latest

#RUN useradd -ms /bin/bash hadoop
#USER hadoop
#WORKDIR /home/hadoop

USER root

# hadoop
RUN curl -s http://www.eu.apache.org/dist/hadoop/common/hadoop-3.1.0/hadoop-3.1.0.tar.gz | tar -xz -C /usr/local
